services:

  automation-exercise-tests:
    image: ${IMAGE_PREFIX}/automation-exercise-tests:latest
    build:
      context: .
      dockerfile: Dockerfile_ci
      args:
        PLAYWRIGHT_VERSION: ${PLAYWRIGHT_VERSION:-1.58.0}
    ports:
      - "6080:6080"
    container_name: automation-exercise-tests
    working_dir: /automation-exercise
    volumes:
      - ./workflow-resources/screenshot:/automation-exercise/src/.screen-output/screenshots/remote
      - ./allure-results:/automation-exercise/build/allure-results
    environment:
      - TEST_ENV=ci
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - TAG_EXPR=${TAG_EXPR}
      - TEST_ARGS=${TEST_ARGS}
      - TEST_ANIMATION_DURATION=${TEST_ANIMATION_DURATION:-1000}
      - TEST_DEFAULT_USER_PASSWORD=${TEST_DEFAULT_USER_PASSWORD}
      - TEST_IGNORE_DISABLED_BY_ISSUE=${TEST_IGNORE_DISABLED_BY_ISSUE:-false}
      - TEST_MAX_SCREENSHOT_DIFF=${TEST_MAX_SCREENSHOT_DIFF:-0.2}
      - TEST_SAVE_FAILED_TESTS_VIDEO=${TEST_SAVE_FAILED_TESTS_VIDEO:-false}
      - TEST_REST_LOGS=${TEST_REST_LOGS:-ALL}
      - TEST_REWRITE_ALL_SCREENSHOTS=${TEST_REWRITE_ALL_SCREENSHOTS:-false}
      - TESTS_PASSED_PERCENTAGE=${TESTS_PASSED_PERCENTAGE}
      - PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION:-1.58.0}
      - PLAYWRIGHT_BROWSER_NAME=${PLAYWRIGHT_BROWSER_NAME}
      - PLAYWRIGHT_BROWSER_TIMEOUT=${PLAYWRIGHT_BROWSER_TIMEOUT:-10000}
      - PLAYWRIGHT_HEADLESS=${PLAYWRIGHT_HEADLESS:-false}
      - PLAYWRIGHT_SLOW_MOTION=${PLAYWRIGHT_SLOW_MOTION:-50.0}
      - GH_TOKEN=${GH_TOKEN}
      - GH_TOKEN_NAME=${GH_TOKEN_NAME}
      - GH_OWNER=${GH_OWNER}
      - GH_REPO=${GH_REPO}
      - HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE}
      - BUILD_URL=${BUILD_URL}
      - EXECUTION_TYPE=${EXECUTION_TYPE}
      - LAST_TEST_STAT_URL=${LAST_TEST_STAT_URL}
    ipc: host
