services:

  automation-exercise-tests:
    image: ${IMAGE_PREFIX}/automation-exercise-tests:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5900:5900"
    container_name: playwright-tests
    container_name: automation-exercise-tests
    working_dir: /automation-exercise
    volumes:
      - ./workflow-resources/screenshot:/rococo/rococo-tests/.screen-output/screenshots/remote
      - ./allure-results:/automation-exercise/build/allure-results
    environment:
      - DISPLAY=${DISPLAY}
      - ALLURE_DOCKER_API=${ALLURE_DOCKER_API}
      - ALLURE_PROJECT_NAME=${ALLURE_PROJECT_NAME}
      - TEST_ENV=${TEST_ENV:-ci}
      - TEST_DEFAULT_USER_PASSWORD=${TEST_DEFAULT_USER_PASSWORD}
      - TEST_IGNORE_DISABLED_BY_ISSUE=${TEST_IGNORE_DISABLED_BY_ISSUE}
      - TEST_MAX_SCREENSHOT_DIFF=${TEST_MAX_SCREENSHOT_DIFF}
      - TEST_SAVE_FAILED_TESTS_VIDEO=${TEST_SAVE_FAILED_TESTS_VIDEO}
      - TEST_REST_LOGS=${TEST_REST_LOGS}
      - TEST_REWRITE_ALL_SCREENSHOTS=${TEST_REWRITE_ALL_SCREENSHOTS}
      - TESTS_PASSED_PERCENTAGE=${TESTS_PASSED_PERCENTAGE}
      - PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION}
      - PLAYWRIGHT_BROWSER_NAME=${PLAYWRIGHT_BROWSER_NAME}
      - PLAYWRIGHT_BROWSER_TIMEOUT=${PLAYWRIGHT_BROWSER_TIMEOUT}
      - PLAYWRIGHT_HEADLESS=${PLAYWRIGHT_HEADLESS}
      - PLAYWRIGHT_SLOW_MOTION=${PLAYWRIGHT_SLOW_MOTION}
      - GH_TOKEN=${GH_TOKEN}
      - GH_TOKEN_NAME=${GH_TOKEN_NAME}
      - GH_OWNER=${GH_OWNER}
      - GH_REPO=${GH_REPO}
      - HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE}
      - BUILD_URL=${BUILD_URL}
      - EXECUTION_TYPE=${EXECUTION_TYPE}
      - LAST_TEST_STAT_URL=${LAST_TEST_STAT_URL}
    ipc: host
