services:

  automation-exercise-tests:
    image: ${IMAGE_PREFIX}/automation-exercise-tests:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLAYWRIGHT_VERSION: ${PLAYWRIGHT_VERSION:-1.58.0}
    ports:
      - "6080:6080"
    container_name: automation-exercise-tests
    working_dir: /automation-exercise
    volumes:
      - ./src/.screen-output/screenshots/docker:/automation-exercise/src/.screen-output/screenshots/docker
      - ./src/.screen-output/video/docker:/automation-exercise/src/.screen-output/video/docker
      - ./allure-results:/automation-exercise/build/allure-results
    cpu_count: 2
    mem_limit: 3500MB
    environment:
      - TEST_ENV=docker
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - ENABLE_VNC=${ENABLE_VNC:-false}
      - VNC_PASS=${VNC_PASS}
      - TAG_EXPR=${TAG_EXPR}
      - TEST_ARGS=${TEST_ARGS}
      - TEST_ANIMATION_DURATION=${TEST_ANIMATION_DURATION:-1000}
      - TEST_DEFAULT_USER_PASSWORD=${TEST_DEFAULT_USER_PASSWORD:-12345}
      - TEST_IGNORE_DISABLED_BY_ISSUE=${TEST_SAVE_FAILED_TESTS_VIDEO:-false}
      - TEST_MAX_SCREENSHOT_DIFF=${TEST_MAX_SCREENSHOT_DIFF:-0.2}
      - TEST_SAVE_FAILED_TESTS_VIDEO=${TEST_SAVE_FAILED_TESTS_VIDEO:-false}
      - TEST_REST_LOGS=${TEST_REST_LOGS:-ALL}
      - TEST_REWRITE_ALL_SCREENSHOTS=${TEST_REWRITE_ALL_SCREENSHOTS:-false}
      - PLAYWRIGHT_BROWSER_NAME=${PLAYWRIGHT_BROWSER_NAME:-chromium}
      - PLAYWRIGHT_BROWSER_SIZE=${PLAYWRIGHT_BROWSER_SIZE:-1920x1080}
      - PLAYWRIGHT_BROWSER_TIMEOUT=${PLAYWRIGHT_BROWSER_TIMEOUT:-10000.0}
      - PLAYWRIGHT_HEADLESS=${PLAYWRIGHT_HEADLESS:-false}
      - PLAYWRIGHT_SLOW_MOTION=${PLAYWRIGHT_SLOW_MOTION:-50.0}
      - GH_TOKEN=${GH_TOKEN}
      - GH_TOKEN_NAME=${GH_TOKEN_NAME}
      - GH_OWNER=${GH_OWNER}
      - GH_REPO=${GH_REPO}
    ipc: host
