name: Screenshot test run

on:
  workflow_dispatch:
    inputs:

      TEST_TITLE:
        description: Test Run Title. Will added in Allure Report Title
        type: string
        required: false
        default: ""

      REWRITE_ALL_SCREENSHOTS:
        description: Rewrite all screenshots
        type: boolean
        required: false
        default: false

      RUN_TESTS_WITH_DEBUG_MARKER:
        description: Run tests with debug marker
        type: boolean
        required: false
        default: false

concurrency:
  group: screenshot-resource
  cancel-in-progress: true

jobs:
  test-run:
    runs-on: ubuntu-latest
    env:
      # ---------- IMPORTANT VARS
      WORKFLOW_REPORT_ID: screenshot_test
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_TOKEN_NAME: ${{ vars.GH_TOKEN_NAME }}
      GH_OWNER: ${{ github.repository_owner }}
      GH_REPO: ${{ vars.GH_REPO }}
      TAG_EXPR: ${{ vars.TAG_EXPR_SCREENSHOT }}
      TEST_ARGS: ${{ vars.TEST_ARGS }}
      TEST_REWRITE_ALL_SCREENSHOTS: ${{ inputs.REWRITE_ALL_SCREENSHOTS }}

      # ---------- BROWSER
      DISPLAY: :0
      TEST_ENV: ${{ vars.TEST_ENV }}
      TEST_DEFAULT_USER_PASSWORD: ${{ secrets.TEST_DEFAULT_USER_PASSWORD }}
      TEST_IGNORE_DISABLED_BY_ISSUE: ${{ vars.TEST_IGNORE_DISABLED_BY_ISSUE }}
      TEST_MAX_SCREENSHOT_DIFF: ${{ vars.TEST_MAX_SCREENSHOT_DIFF }}
      TEST_SAVE_FAILED_TESTS_VIDEO: ${{ vars.TEST_SAVE_FAILED_TESTS_VIDEO }}
      TEST_REST_LOGS: ${{ vars.TEST_REST_LOGS }}
      TESTS_PASSED_PERCENTAGE: ${{ inputs.REWRITE_ALL_SCREENSHOTS }}
      PLAYWRIGHT_VERSION: ${{ vars.PLAYWRIGHT_VERSION }}
      PLAYWRIGHT_BROWSER_NAME: ${{ vars.PLAYWRIGHT_BROWSER_NAME }}
      PLAYWRIGHT_BROWSER_TIMEOUT: ${{ vars.PLAYWRIGHT_BROWSER_TIMEOUT }}
      PLAYWRIGHT_HEADLESS: ${{ vars.PLAYWRIGHT_HEADLESS }}
      PLAYWRIGHT_SLOW_MOTION: ${{ vars.PLAYWRIGHT_SLOW_MOTION }}
      BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      EXECUTION_TYPE: github

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}

      - name: Get the last commit message
        run: |
          echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Ensure workflow-resources branch exists
        run: |
          set -e

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git ls-remote --exit-code --heads origin workflow-resources > /dev/null; then
            echo "Branch workflow-resources exists"
          else
            echo "Branch workflow-resources does not exist. Creating empty branch..."

            git checkout --orphan workflow-resources
            git rm -rf .

            git commit --allow-empty -m "chore: initialize workflow-resources branch"
            git push origin workflow-resources

            git checkout -
          
          fi

      - name: Checkout workflow-resources branch
        uses: actions/checkout@v4
        with:
          ref: workflow-resources
          path: workflow-resources

      - name: Prepare workflow-resources directory
        run: |
          set -e
          mkdir -p workflow-resources/screenshot

      - name: Run SCREENSHOT tests
        uses: ./.github/actions/run-tests
        if: always()
        continue-on-error: true

      - name: Generate and Deploy Allure Report in GitHub Pages
        uses: ./.github/actions/generate-and-deploy-allure-report
        if: always()
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          subfolder: ${{ env.WORKFLOW_REPORT_ID }}
          report_name: PR ${{ github.event.pull_request.number }} Report
          allure_results_path: allure-results
          allure_history_path: allure-history
          report_branch: gh-pages

      - name: Commit workflow-resources changes
        if: always()
        run: |
          set -e
          cd workflow-resources

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit in workflow-resources"
            exit 0
          fi

          git commit -m "chore: update workflow resources (screenshots)"
          git push origin workflow-resources
